spring:
  datasource:
    rsk1:
      driver-class-name: oracle.jdbc.OracleDriver
      # url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.255.253.8)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=his8.wyyy.com)))
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.104.141.152)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=test)))
      username: rsk1
      password: wwwwfffyyy
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 http://localhost:8080/druid/index.html 查看sql监控
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      ###############以上为配置druid添加的配置########################################
    ylgz3:
      driver-class-name: oracle.jdbc.OracleDriver
      # url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.255.253.8)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=his8.wyyy.com)))
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.104.141.152)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=test)))
      username: ylgz3
      password: wwwwfffyyy
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 http://localhost:8080/druid/index.html 查看sql监控
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
        ###############以上为配置druid添加的配置########################################
      ###################以下为druid增加的配置###########################
    # 下面为连接池的补充设置，应用到上面所有数据源中
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
#  aop:
#    proxy-target-class: true